services:
  web: 
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/var/www/html/frontend/dist
      - ./backend:/var/www/html/backend
      - ./.develop/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - psychology-network
  
  php-fpm:
    build: .
    container_name: laravel
    image: php:8.2.12-fpm
    working_dir: /var/www/html
    env_file:
      - ./.env
    volumes:
      - ./backend:/var/www/html
    networks: 
      - psychology-network
    # ports:
    #   - 9000:9000

  db:
    image: mysql:9.5.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: psychologist_db
      MYSQL_USER: psychologist_user
      MYSQL_PASSWORD: psychology_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.develop/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - psychology-network
    
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_HOST: db
      ADMINER_DESIGN: dracula
    networks:
      - psychology-network
    depends_on:
      - db

networks:
  psychology-network:
    driver: bridge

volumes:
  mysql_data: